export const company = {
  name: "MartEX", tagline: "Technology That Solves Business", location: "Monrovia, Liberia", established: 2026,
  description: "MartEX builds practical software solutions that help organizations improve operations, automate work, manage information, and serve customers more effectively.",
  email: "[Email to be provided]", phone: "[Telephone to be provided]", website: "[Website address to be provided]", hours: "[Business hours to be provided]"
};

export type Service = {slug:string; title:string; short:string; intro:string; capabilities:string[]; problems:string[]; useCases:string[]};
export const services: Service[] = [
  ["custom-software-development","Custom Software Development","Purpose-built systems shaped around your workflows, people, and growth plans.","Replace workarounds with dependable software that fits how your organization actually operates.",["Requirements mapping","Role-based workflows","Dashboards and reporting","Testing and handover"],["Generic tools do not fit","Critical work depends on spreadsheets","Teams repeat the same data entry"],["Operations platforms","Case-management systems","Internal business tools"]],
  ["web-application-development","Web Application Development","Secure, responsive portals, dashboards, internal systems, and online services.","Deliver useful digital services through fast, accessible web applications.",["Customer and staff portals","Responsive interfaces","Administration tools","Secure access controls"],["Services are difficult to access","Information is spread across channels","Legacy interfaces slow teams down"],["Self-service portals","Management dashboards","Online service platforms"]],
  ["mobile-application-development","Mobile Application Development","Mobile tools for customers, employees, field teams, and service delivery.","Put the right workflow in people’s hands, wherever the work happens.",["Cross-platform applications","Offline-ready workflows","Notifications","Field data capture"],["Field work relies on paper","Users need access away from desks","Updates reach teams slowly"],["Field operations","Customer apps","Staff tools"]],
  ["business-process-automation","Business Process Automation","Digital workflows that reduce repetition, improve consistency, and accelerate operations.","Turn multi-step manual processes into visible, reliable workflows.",["Workflow mapping","Rules and approvals","Notifications","Audit trails"],["Approvals stall","Tasks are duplicated","Process status is unclear"],["Request approvals","Onboarding workflows","Service fulfilment"]],
  ["information-management-systems","Information Management Systems","Applications for collecting, organizing, reporting, and protecting information.","Create a dependable source of information for everyday work and better decisions.",["Structured records","Search and retrieval","Reporting","Permissions and retention"],["Records are fragmented","Reporting takes too long","Access is inconsistent"],["Program records","Document registers","Operational reporting"]],
  ["systems-integration","Systems Integration","Connections between applications, databases, payments, APIs, and approved platforms.","Help systems exchange information safely so teams can work from a connected picture.",["API integration","Data synchronization","Payment connections","Integration monitoring"],["Teams re-enter data","Systems disagree","Handoffs create delays"],["Payment workflows","Cross-system reporting","Platform connectors"]],
  ["technology-consulting","Technology Consulting","Business analysis, requirements definition, solution planning, and transformation guidance.","Make sound technology decisions with a practical path from challenge to implementation.",["Operational discovery","Requirements definition","Solution architecture","Delivery roadmaps"],["The right solution is unclear","Requirements are incomplete","Technology investments lack a plan"],["Digital roadmaps","Vendor-neutral planning","Project discovery"]]
].map(([slug,title,short,intro,capabilities,problems,useCases])=>({slug,title,short,intro,capabilities,problems,useCases})) as Service[];

export type Solution={slug:string;title:string;challenge:string;industries:string[];features:string[]};
export const solutions: Solution[]=[
 ["customer-management","Sales & customer management","Organize relationships, follow-ups, and service history.",["SMEs","Corporate"],["Customer records","Pipeline views","Follow-up workflows"]],
 ["inventory-purchasing","Inventory & purchasing","Understand stock movement and coordinate purchasing.",["Retail","Healthcare","SMEs"],["Stock records","Purchase workflows","Movement reports"]],
 ["billing-payments","Billing & payment tracking","Bring invoices and payment status into one clear workflow.",["SMEs","Institutions"],["Invoices","Payment status","Account summaries"]],
 ["people-operations","HR & staff management","Support attendance, employee records, and routine people operations.",["Corporate","NGOs","Institutions"],["Staff records","Attendance","Requests and approvals"]],
 ["records-workflow","Records, cases & workflows","Keep documents, cases, and decisions connected and retrievable.",["Government","NGOs","Healthcare"],["Case records","Document control","Workflow status"]],
 ["reporting-dashboards","Dashboards & reporting","Turn operational information into decision-ready views.",["All organizations"],["Role-based dashboards","Report exports","Data quality views"]],
 ["field-programs","Field data & program management","Coordinate collection, monitoring, and program work across locations.",["NGOs","Healthcare","Government"],["Field capture","Program tracking","Monitoring views"]]
].map(([slug,title,challenge,industries,features])=>({slug,title,challenge,industries,features})) as Solution[];

export const process=["Discovery","Planning","Design","Development","Deployment","Support"];
export const values=["Problem solving","Reliability","Simplicity","Integrity","Continuous improvement","Partnership"];
export const audiences=["SMEs","Corporate teams","Government institutions","NGOs and development organizations","Educational institutions","Healthcare organizations","Startups"];
export const commitments=["Clear requirements and agreed scope","Regular communication and review points","Appropriate usability, functional, security, and performance testing","Responsible handling of client data and access credentials","Documentation, training, and handover","Defined maintenance and change-management arrangements"];
